version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  gremlin:
    image: tinkerpop/gremlin-server:3.7.3
    container_name: rag-gremlin
    ports:
      - "8182:8182"

  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"


